In [9]:
import pandas as pd

df = pd.read_csv("all_scores_new_v7.csv")

df = df.drop(columns=[col for col in df.columns if 'Unnamed' in col])
df = df.drop(columns=['tmp', 'itr'])

mean_values = df.drop(columns=['sub_cat', "dataset"]).groupby(['model', 'cat']).mean()
mean_values
#
# df = df[df['dataset'] == 'spider']

# df = df.groupby(['model', "dataset", "tmp", "cat", "sub_cat"])
#
# df = df.mean()

                 em        ea       gne       rea            et       sem  \
model cat
dail  c1   0.910675  0.898693  1.000000  0.954248    541.098039  0.913377
      c2   0.717928  0.763132  0.988482  0.857799  14268.822582  0.628274
      c3   0.449702  0.638200  0.963082  0.767936  15826.349009  0.415054
      c4   0.351510  0.519738  0.908596  0.631659  70811.250130  0.362591
      c5   0.266285  0.516683  0.969298  0.578329  72881.947887  0.440058
      c6   0.175936  0.402194  0.736842  0.432085  66180.992433  0.000000
din   c1   0.897603  0.918301  1.000000  0.966231    464.129630  0.903509
      c2   0.619133  0.753944  0.988482  0.835497  14882.780108  0.614197
      c3   0.364205  0.632237  0.963082  0.747163  15726.133680  0.383513
      c4   0.265487  0.492061  0.908596  0.601466  67001.070753  0.343422
      c5   0.266285  0.499206  0.969298  0.568478  86819.849698  0.421784
      c6   0.074537  0.372304  0.736842  0.407870  75663.983731  0.008772

                 cc            get        tokens       ds_idx
model cat
dail  c1   0.940087     570.576253   2299.828976  4829.607843
      c2   0.858731   15210.662007   3086.443379  4567.237667
      c3   0.865936   20798.942777   4145.596461  4536.730237
      c4   0.875499   70875.576132   6043.153783  4532.664107
      c5   0.924372   85488.722593   7712.495392  4315.316492
      c6   0.917140  275192.608021  10938.623912  3934.729852
din   c1   0.922658     517.834423   9687.889978  4829.607843
      c2   0.825977   19911.206311  13009.018707  4567.237667
      c3   0.751587   25486.524812  14115.167532  4536.730237
      c4   0.763361   82174.964819  21561.785919  4532.664107
      c5   0.906895   92007.884017  18528.720686  4315.316492
      c6   0.881574  261423.838820  25159.620129  3934.729852

In [10]:

mean_values = mean_values.groupby(['model']).mean()
mean_values

,em,ea,gne,rea,et,sem,cc,get,tokens,ds_idx
model,,,,,,,,,,
dail,0.478673,0.623107,0.927717,0.703676,40085.07668,0.459892,0.896961,78022.847964,5704.356984,4452.714366
din,0.414542,0.611342,0.927717,0.687784,43426.32460,0.445866,0.842009,80253.708867,17010.367159,4452.714366

Unnamed: 0.6                                          15283813077
Unnamed: 0.5    dail_beaver_0dail_beaver_1dail_beaver_2dail_be...
Unnamed: 0.3                                           1492176816
Unnamed: 0.2                                           1492176816
Unnamed: 0.1                                           1245768978
Unnamed: 0                                            415228786.0
tmp                                                       22071.6
itr                                                        110358
cat             c4c6c4c4c6c6c6c6c4c6c6c4c4c4c5c6c6c4c4c4c5c6c6...
sub_cat         s28s35s28s28s35s35s35s35s28s37s37s28s28s28s31s...
em                                                          46768
ea                                                          66234
gne                                                       52944.0
rea                                                         77207
et                                                   4821219188.0
sem                                                       27583.0
cc                                                          92131
get                                                  6514821197.0
tokens                                                 1256987922
ds_idx                                                  497355486
Unnamed: 0.4                                          746088408.0
dtype: object